version: '3.4'

networks:
  appnet:
    driver: bridge

services:
  app:
    image: host
    depends_on:
      - 'pg'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    networks:
      - appnet
    restart: always

  pg:
    image: postgres
    ports:
      - '5432:5432'
    restart: always
    environment:
     - POSTGRES_USER=easyadmin
     - POSTGRES_PASSWORD=password
     - POSTGRES_DB=easyadmin
    networks:
      - appnet